In [3]:
import numpy as np

In [4]:
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [8]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [9]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr[:,1:2] ## start_row:end_row,start_col:end_column

array([[2],
       [5],
       [8]])

In [28]:
arr[:,2:3]

array([[3],
       [6],
       [9]])

In [31]:
arr[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [42]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [45]:
np.eye(3,3).astype(int).dtype

dtype('int32')

In [46]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [60]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[a>2]

array([3, 4])

In [58]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
### Vector operations with scaler values

In [66]:
a = np.array([1,2,3])
a*2

array([2, 4, 6])

In [67]:
a**2

array([1, 4, 9])

In [68]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [70]:
a+b

array([[ 6,  8],
       [10, 12]])

In [71]:
a*b

array([[ 5, 12],
       [21, 32]])

In [72]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [74]:
#Transpoe

In [80]:
a.T

array([[1, 3],
       [2, 4]])

In [81]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [82]:
np.linalg.det(a)

-2.0000000000000004

In [84]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [85]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [87]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [88]:
a

array([[1, 2],
       [3, 4]])

In [91]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [92]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [119]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 4,  1]])

In [120]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [121]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1],
       [ 1,  2,  3,  4]])

In [122]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [131]:
b = arr.view()

In [132]:
b[0] = 10

In [133]:
arr

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [134]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [135]:
c = arr.copy()

In [138]:
arr, c

(array([[10, 10, 10],
        [ 4,  5,  6],
        [ 7,  8,  9]]),
 array([[10, 10, 10],
        [ 4,  5,  6],
        [ 7,  8,  9]]))

In [150]:
c[0] = 11

In [155]:
array = ([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [156]:
a is b

False

In [157]:
import statistics
data = [1,2,3,4,5]
mean = statistics.mean(data)
print(mean)

3


In [158]:
def mean(array):
    n = len(array)
    return np.sum(array)/n

In [159]:
mean(np.array([1,2,3,4,5,6]))

3.5

In [164]:
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array - m)**2)/n

In [165]:
variance(np.array([1,2,3,4,5,6]))

2.9166666666666665

In [177]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
xmin, xmax = x.min(), x.max()
minmax = (x - xmin) / (xmax - xmin)
print(minmax)

[0.   0.25 0.5  0.75 1.  ]


In [172]:
import numpy as np
x = np.array([1,2,3,4,5])
mean = x.mean()
(x - mean)/x.std()

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [175]:
import numpy as np
x = np.array([0,1,2,3])
1/(1 + np.exp(-x))

array([0.5       , 0.73105858, 0.88079708, 0.95257413])

In [176]:
import numpy as np
x = np.array([1,2,3,4,5])
np.maximum(0,x)

array([1, 2, 3, 4, 5])